.TH "" "1" "July 2025"
.SH NAME
.P
tnascert\-deploy \- A tool used to deploy UI certificates to a TrueNAS host
.SS SYNOPSIS
.P
tnascert\-deploy [\-h] [\-c value] section_name \.\.\. section_name<br>
.P
\-c, \-\-config="full path to tnas\-cert\.ini file"<br>
.br
\-h, \-\-help<br>
.br
\-v, \-\-version<br>
.SS DESCRIPTION
.P
A tool used to import a TLS certificate and private key into a TrueNAS
.br
SCALE host running \fI\fBTrueNAS 25\.04\fR\fR or later\.  Once imported, the tool
.br
may be configred to activate the TrueNAS host to use it as the main UI
.br
TLS certificate\.
.P
The \fI\fBtnas\-cert\.ini\fR\fR file consists of multiple <b>sections</b>
.br
The optional command line arguments \fI\fBsection_name\fR\fR may by
.br
used to load that particular configuration\.  This allows for maintaining
.br
multiple configurations in one tnas\-cert\.ini file where
.br
each \fI\fBsection_name\fR\fR may be an individual \fI\fBTrueNAS\fR\fR host\.
.br
You may list multiple \fI\fB_section_name\fR\fR on the command line to loop
.br
through certificate installation on multiple \fI\fBTrueNAS\fR\fR hosts\.
.P
If the optional argument \fI\fBsection_name\fR\fR is not provided, The
.br
\fI\fBdeploy_default\fR\fR section name is chosen to load the configuration if
.br
it exists\.
.P
For client authentication, you may use either a TrueNAS \fI\fBapi_key\fR\fR or
.br
the \fI\fBusername\fR\fR and \fI\fBpassword\fR\fR for user with admin privileges\. The
.br
\fI\fBapi_key\fR\fR is the preferred method for authentication\.  If all three
.br
variables are set in a configuration, the \fI\fBapi_key\fR\fR login method will
.br
always be used\.  If you prefer to use the \fI\fBusername\fR\fR and \fI\fBpassword\fR\fR
.br
ensure only the \fI\fBusername\fR\fR and \fI\fBpassword\fR\fR are set in your configuration\.
.P
See the sample \fBtnas\-cert\.ini\fR file\.
.SS FILES
.P
The default configuration file is named \fI\fBtnas\-cert\.ini\fR\fR in the current working
.br
directory\.  You may use the command line switch to use another file name and full
.br
path to the config file\.
.SS CONFIG FILE SETTINGS
.RS 2
.nf
+ api_key                string  \- TrueNAS 64 byte API Key for login (preferred login method)\.
+ username               string  \- TrueNAS username with admin privileges (API key is preferred for login)
+ password               string  \- TrueNAS password for user with admin privileges, (API key is preferred for login)
+ cert_basename          string  \- basename for cert naming in TrueNAS
+ connect_host           string  \- TrueNAS DNS Fully Qualified Domain Name, FQDN, or IP address
+ delete_old_certs       bool    \- whether to remove old certificates, default is false
+ full_chain_path        string  \- path to full_chain\.pem
+ port                   uint64  \- TrueNAS API endpoint port
+ protocol               string  \- websocket protocol 'ws' or 'wss' wss' is default
+ private_key_path       string  \- path to private_key\.pem
+ tls_skip_verify        bool    \- strict SSL cert verification of the endpoint, false by default
+ add_as_ui_certificate  bool    \- install as the active UI certificate if true
+ add_as_ftp_certificate bool    \- install as the active FTP service certificate if true
+ add_as_app_certificate bool    \- install as the active APP service certificate if true
+ timeoutSeconds         int64   \- the number of seconds after which the truenas client calls fail
+ debug                  bool    \- debug logging if true
.fi
.RE
.SS NOTES
.P
This tool uses the TrueNAS Scale JSON\-RPC 2\.0 API and the TrueNAS client API module\. Supports versions of \fI\fBTrueNAS 25\.04\fR\fR or later
.P
See Also:

.RS 1
.IP \(bu 2
.UR https://github.com/truenas/api_client_golang
.I TrueNAS api_client_golang
.UE
.IP \(bu 2
.UR https://www.truenas.com/docs/api/scale_websocket_api.html
.I TrueNAS websocket API documentaion
.UE

.RE
.P
Clone this repository and build the tool using \fI\fBgo build\fR\fR
.SS Contact
.P
John J\. Rushford<br>
.br
jrushford@apache.org

